# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dronetask_display.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets
from CustomTitleBar import CustomTitleBar
from MainContentLayout import MainContentLayout

class Drone_Ui(object):
    def setupUi(self, 
                Form:QtWidgets.QMainWindow
                ):
        Form.setObjectName("Form")
        Form.resize(1351, 815)
        Form.setStyleSheet("background-color: white;")
        """
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(10, 10, 1011, 531))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(10, 550, 331, 241))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(350, 550, 331, 241))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_4 = QtWidgets.QFrame(Form)
        self.frame_4.setGeometry(QtCore.QRect(690, 550, 331, 241))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        """

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))

class Drone_Window(QtWidgets.QMainWindow,Drone_Ui):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.setWindowFlags(QtCore.Qt.FramelessWindowHint)

        self.title_bar=CustomTitleBar()
        central_widget = QtWidgets.QWidget()
        layout = QtWidgets.QVBoxLayout(central_widget)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.addWidget(self.title_bar)
        
        self.title_bar.btn_min.clicked.connect(self.showMinimized)
        self.title_bar.layout.addWidget(self.title_bar.btn_min)

        self.title_bar.btn_max_restore.clicked.connect(self.toggle_max_restore)
        self.title_bar.layout.addWidget(self.title_bar.btn_max_restore)
        
        self.title_bar.btn_close.clicked.connect(self.close)
        self.title_bar.layout.addWidget(self.title_bar.btn_close)

        self.content = MainContentLayout()
        layout.addWidget(self.content)

        self.setCentralWidget(central_widget)

    def toggle_max_restore(self):
        if self.isMaximized():
            self.showNormal()
            self.title_bar.btn_max_restore.setIcon(QtGui.QIcon("icons/maximise.png"))
        else:
            self.showMaximized()
            self.title_bar.btn_max_restore.setIcon(QtGui.QIcon("icons/restore-down.png"))

    #向聊天框中添加消息
    def add_message(self,text,user):
        self.content.chat.messagedisplay.add_message(text,user)